'use client';

import { useState } from 'react';
import { Sparkles, X, Bot, ArrowRight, CheckCircle2, Zap, Brain, RefreshCw } from 'lucide-react';

export default function AiCopilotDrawer({ isOpen, onClose, onTasksGenerated }) {
  const [activeTab, setActiveTab] = useState('breakdown');
  const [loading, setLoading] = useState(false);
  const [aiData, setAiData] = useState(null);

  const fetchAiInsights = async (type) => {
    setLoading(true);
    try {
      const res = await fetch('/api/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ promptType: type })
      });
      const data = await res.json();
      setAiData(data);
    } catch (err) {
      console.error("AI Copilot error:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleApplyTasks = async () => {
    if (!aiData?.suggestedTasks) return;
    try {
      for (const t of aiData.suggestedTasks) {
        await fetch('/api/tasks', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            title: t.title,
            projectId: 'proj-1',
            status: 'todo',
            priority: t.priority || 'medium',
            assigneeId: t.assigneeId || 'mem-1',
            estimatedHours: t.estimatedHours || 8,
            description: 'Auto-generated by NOVA AI Copilot'
          })
        });
      }
      if (onTasksGenerated) onTasksGenerated();
      onClose();
    } catch (err) {
      console.error("Error creating AI tasks:", err);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="glass-panel w-full max-w-lg h-full border-l border-indigo-500/30 flex flex-col justify-between shadow-2xl p-6 relative z-10 overflow-hidden">
        <div className="absolute top-0 right-0 w-80 h-80 bg-gradient-to-bl from-indigo-500/20 via-sky-500/10 to-transparent blur-3xl pointer-events-none" />

        {/* Drawer Header */}
        <div>
          <div className="flex items-center justify-between pb-4 border-b border-slate-800 mb-4">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-sky-500 to-indigo-600 flex items-center justify-center shadow-glow-cyan">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              <div>
                <h2 className="font-bold text-base text-white flex items-center gap-1.5">
                  <span>NOVA AI Copilot</span>
                  <span className="px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 text-[10px] font-bold border border-indigo-500/30">
                    v2.4
                  </span>
                </h2>
                <p className="text-[11px] text-slate-400">Intelligent sprint optimization & project automation</p>
              </div>
            </div>
            <button onClick={onClose} className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800">
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Action Tabs */}
          <div className="grid grid-cols-3 gap-2 mb-6">
            <button
              onClick={() => { setActiveTab('breakdown'); fetchAiInsights('task_breakdown'); }}
              className={`p-2.5 rounded-xl border text-xs font-semibold flex flex-col items-center gap-1 transition-all ${
                activeTab === 'breakdown' ? 'bg-sky-500/20 text-sky-400 border-sky-500/40 shadow-glow-cyan' : 'bg-slate-900/60 text-slate-400 border-slate-800'
              }`}
            >
              <Zap className="w-4 h-4" />
              <span>Auto Breakdown</span>
            </button>

            <button
              onClick={() => { setActiveTab('workload'); fetchAiInsights('workload_optimization'); }}
              className={`p-2.5 rounded-xl border text-xs font-semibold flex flex-col items-center gap-1 transition-all ${
                activeTab === 'workload' ? 'bg-indigo-500/20 text-indigo-400 border-indigo-500/40 shadow-glow-purple' : 'bg-slate-900/60 text-slate-400 border-slate-800'
              }`}
            >
              <Brain className="w-4 h-4" />
              <span>Risk Analysis</span>
            </button>

            <button
              onClick={() => { setActiveTab('report'); fetchAiInsights('status_report'); }}
              className={`p-2.5 rounded-xl border text-xs font-semibold flex flex-col items-center gap-1 transition-all ${
                activeTab === 'report' ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40 shadow-glow-emerald' : 'bg-slate-900/60 text-slate-400 border-slate-800'
              }`}
            >
              <Bot className="w-4 h-4" />
              <span>Exec Report</span>
            </button>
          </div>

          {/* Copilot Result Body */}
          <div className="space-y-4 max-h-[calc(100vh-280px)] overflow-y-auto pr-1">
            {loading ? (
              <div className="p-8 text-center space-y-3">
                <RefreshCw className="w-6 h-6 text-sky-400 animate-spin mx-auto" />
                <p className="text-xs text-slate-400">Synthesizing project analytics & workload vectors...</p>
              </div>
            ) : aiData ? (
              <div className="space-y-4">
                {activeTab === 'breakdown' && aiData.suggestedTasks && (
                  <div className="space-y-3">
                    <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/80 p-3 rounded-xl border border-slate-800">
                      {aiData.aiSummary}
                    </p>
                    <div className="space-y-2">
                      {aiData.suggestedTasks.map((t, idx) => (
                        <div key={idx} className="p-3 rounded-xl bg-slate-900/60 border border-slate-800/80 text-xs flex justify-between items-center">
                          <div>
                            <span className="font-semibold text-slate-200 block">{t.title}</span>
                            <span className="text-[10px] text-slate-400">Est. {t.estimatedHours} hrs • Priority: {t.priority}</span>
                          </div>
                          <span className="px-2 py-0.5 rounded bg-sky-500/20 text-sky-400 text-[10px] font-bold">Auto</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {activeTab === 'workload' && (
                  <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-indigo-400">Workload Optimization Vector</span>
                      <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-400 text-[10px] font-bold">Score: 94/100</span>
                    </div>
                    <p className="text-xs text-slate-300 leading-relaxed">
                      {aiData.recommendation}
                    </p>
                  </div>
                )}

                {activeTab === 'report' && (
                  <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                    <span className="text-xs font-bold text-emerald-400">Generated Sprint Executive Briefing</span>
                    <p className="text-xs text-slate-300 leading-relaxed font-mono text-[11px] whitespace-pre-line bg-black/40 p-3 rounded-lg border border-slate-800">
                      {`### NOVA Sprint Summary Report\n- Active Engineering Streams: 4\n- Completion Velocity: +18% ahead of target\n- Overall Health Index: 94.2%\n- Key Milestone Achieved: Design System & JWT Auth API completed.`}
                    </p>
                  </div>
                )}
              </div>
            ) : (
              <div className="p-8 text-center text-xs text-slate-500 border border-dashed border-slate-800 rounded-2xl">
                Click any AI action tab above to generate real-time intelligent recommendations.
              </div>
            )}
          </div>
        </div>

        {/* Footer Actions */}
        {activeTab === 'breakdown' && aiData?.suggestedTasks && (
          <button
            onClick={handleApplyTasks}
            className="w-full py-3 rounded-xl bg-gradient-to-r from-sky-500 to-indigo-600 hover:from-sky-400 hover:to-indigo-500 text-white font-bold text-xs shadow-glow-cyan flex items-center justify-center gap-2 transition-all mt-4"
          >
            <CheckCircle2 className="w-4 h-4" />
            <span>Apply 4 Suggested Tasks to Kanban</span>
          </button>
        )}
      </div>
    </div>
  );
}
